kind: pipeline
name: default
type: docker

steps:
  - name: compile
    image: maven:3-jdk-8
    commands:
      - mvn compile -B -U
  - name: test
    image: maven:3-jdk-8
    commands:
      - mvn test -B
