kind: pipeline
image: maven:3.6.3-jdk-8
name: default
type: docker


steps:
pipelines:
  name: compile
  default:
    image: maven:3-jdk-8
    - step:
    commands:
        caches:
      - mvn compile -B -U
          - maven
    name: test
        script: # Modify the commands below to build your repository.
    image: maven:3-jdk-8
          - mvn -B verify # -B batch mode makes Maven less verbose
    commands:
      - mvn test -B